import { 
  Hammer, 
  BarChart3, 
  Settings, 
  Pin, 
  Star, 
  ClipboardList, 
  Layout, 
  Code2, 
  Clock, 
  Map, 
  LayoutDashboard, 
  PieChart, 
  FileText, 
  Folder, 
  Users, 
  MessageSquare, 
  AtSign, 
  Hash, 
  Users2, 
  Search, 
  File,
  RefreshCw,
  Package,
  Users as TeamIcon,
  Building2,
  Target,
  Tag,
  Clock3,
  CheckCircle2,
  ArrowRightLeft,
  Bookmark,
  Briefcase,
  TrendingUp,
  Sliders,
  Star as StarIcon,
  Pin as PinIcon
} from 'lucide-react';

export const NEW_GLOBAL_NAV = [
  { id: 'issues', icon: ClipboardList, label: 'ISSUES' },
  { id: 'boards', icon: Layout, label: 'BOARDS' },
  { id: 'code-prs', icon: Code2, label: 'CODE & PRs' },
  { id: 'time-tracker', icon: Clock, label: 'TIME TRACKER' },
  { id: 'roadmap', icon: Map, label: 'ROADMAP' },
  { id: 'reports', icon: FileText, label: 'REPORTS' },
  { id: 'members', icon: Users, label: 'MEMBERS' },
  { id: 'analytics', icon: BarChart3, label: 'ANALYTICS' },
  { id: 'insights', icon: TrendingUp, label: 'INSIGHTS' },
  { id: 'chat', icon: MessageSquare, label: 'CHAT' },
];

export const NAVIGATION_TREE = {
  issues: [
    { id: 'assigned-to-me', label: 'Assigned to me' },
    { id: 'reported-by-me', label: 'Reported by me' },
    { id: 'mentioned-me', label: 'Mentioned me' },
    { id: 'following', label: 'Following' },
  ],
  boards: [
    { id: 'sprint-board', label: 'Sprint Board' },
    { id: 'kanban-board', label: 'Kanban Board' },
    { id: 'product-backlog', label: 'Product Backlog' },
    { id: 'sprint-planning', label: 'Sprint Planning' },
    { id: 'defect-board', label: 'Defect Board' },
    { id: 'release-board', label: 'Release Board' },
    { id: 'story-map', label: 'Story Map' },
    { id: 'epic-progress', label: 'Epic Progress' },
  ],
  'code-prs': [
    { id: 'pull-requests', label: 'Pull Requests' },
    { id: 'my-prs', label: 'My PRs' },
    { id: 'review-requests', label: 'Review Requests' },
    { id: 'branches', label: 'Branches' },
    { id: 'recent-commits', label: 'Recent Commits' },
  ],
  'time-tracker': [
    { id: 'active-timer', label: 'Active Timer' },
    { id: 'today-log', label: "Today's Log" },
    { id: 'timesheet', label: 'Timesheet' },
    { id: 'approvals', label: 'Approvals' },
  ],
  roadmap: [
    { id: 'timeline', label: 'Timeline' },
    { id: 'initiative', label: 'Initiative' },
    { id: 'milestone', label: 'Milestone' },
    { id: 'dependency', label: 'Dependency' },
  ],
  reports: [
    { id: 'status-reports', label: 'Status Reports' },
    { id: 'timesheet-reports', label: 'Timesheet Reports' },
    { id: 'project-summary', label: 'Project Summary' },
    { id: 'portfolio-summary', label: 'Portfolio Summary' },
  ],
  members: [
    { id: 'all-members', label: 'All Members' },
    { id: 'teams', label: 'Teams' },
    { id: 'invitations', label: 'Invitations' },
  ],
  analytics: [
    { id: 'velocity-trend', label: 'Velocity Trend' },
    { id: 'cycle-time', label: 'Cycle Time' },
    { id: 'throughput', label: 'Throughput' },
    { id: 'status-dist', label: 'Status Distribution' },
  ],
  insights: [
    { id: 'dashboard', label: 'Dashboard' },
    { id: 'velocity-analytics', label: 'Velocity Analytics' },
    { id: 'cycle-time-analytics', label: 'Cycle Time Analytics' },
    { id: 'predictability', label: 'Predictability' },
  ],
  chat: [
    { id: 'messages', label: 'Messages' },
    { id: 'files', label: 'Files' },
    { id: 'pins', label: 'Pins' },
    { id: 'huddle', label: 'Huddle' },
  ]
};
